### ISSUE TITLE
Convention Card Editor: 1NT-2S not set by boolean

### ISSUE THREAD

**Issue by bruce2-50** [mycroftw/conv-cards#68]
For the 2022 LaTeX convention card editor by Michael Farebrother, it looks like there is a glitch in acbl2022cc.sty.

In the 1NT section, the 2S response is always a transfer. Can't toggle it off. Removing or adding the % has no effect.

**Comment by mycroftw** [comment]
Yeah, it looks like I messed up the copy-paste here.  The box triggers on the heart transfer.  Easy fix, but I'll be careful to be consistent here.

**Comment by mycroftw** [comment]
Try the 68-1nt-2s-not-set-by-boolean branch.  I'm going to add two "alternate checkboxes" test cards to check for other cut-paste anomalies like this one before merging in, but this problem (and the diamonds -> hearts one) should be fixed now.

**Comment by mycroftw** [comment]
Merged via pull request #70.
